name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate package
        uses: heyhusen/archlinux-package-action@v2.2.1
        with:
          aur: true